In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler

In [2]:
from google.colab import files

uploaded = files.upload()

Saving Day12_Used_Car_Preprocessing_Dataset.csv to Day12_Used_Car_Preprocessing_Dataset.csv

In [3]:
file_name = list(uploaded.keys())[0]

df = pd.read_csv(file_name)

df.head()

,Car_ID,Brand,Year,Mileage_Km,Engine_CC,Power_BHP,Fuel_Type,Transmission,City,Seller_Type,Condition,Previous_Owners,Accidents_Reported,Service_Score,Resale_Price_Lakh
0,CAR0001,Skoda,2021,69708,1152,128.8,Diesel,Manual,Lucknow,Individual,Good,1,0,72,6.38
1,CAR0002,Toyota,2020,88881,903,146.5,Diesel,Automatic,Chandigarh,Individual,Good,1,0,87,4.83
2,CAR0003,Volkswagen,2021,43646,1446,185.9,Diesel,Automatic,Hyderabad,Individual,Very Good,2,0,90,7.30
3,CAR0004,Tata,2019,70847,2069,148.8,Petrol,Manual,Lucknow,Individual,Excellent,3,0,66,3.82
4,CAR0005,Tata,2016,101228,1657,206.0,Petrol,Automatic,Ahmedabad,Dealer,Very Good,2,0,84,1.93

In [4]:
print("Dataset Shape:", df.shape)

print("\nColumn Names:")
print(df.columns)

print("\nDataset Information:")
df.info()

Dataset Shape: (320, 15)

Column Names:
Index(['Car_ID', 'Brand', 'Year', 'Mileage_Km', 'Engine_CC', 'Power_BHP',
       'Fuel_Type', 'Transmission', 'City', 'Seller_Type', 'Condition',
       'Previous_Owners', 'Accidents_Reported', 'Service_Score',
       'Resale_Price_Lakh'],
      dtype='object')

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Car_ID              320 non-null    object
 1   Brand               320 non-null    object
 2   Year                320 non-null    int64
 3   Mileage_Km          320 non-null    int64
 4   Engine_CC           320 non-null    int64
 5   Power_BHP           320 non-null    float64
 6   Fuel_Type           320 non-null    object
 7   Transmission        320 non-null    object
 8   City                320 non-null    object
 9   Seller_Type         320 non-null    object
 10  Condition           320 non-null    object
 11  Previous_Owners     320 non-null    int64
 12  Accidents_Reported  320 non-null    int64
 13  Service_Score       320 non-null    int64
 14  Resale_Price_Lakh   320 non-null    float64
dtypes: float64(2), int64(6), object(7)
memory usage: 37.6+ KB

In [5]:
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
Car_ID                0
Brand                 0
Year                  0
Mileage_Km            0
Engine_CC             0
Power_BHP             0
Fuel_Type             0
Transmission          0
City                  0
Seller_Type           0
Condition             0
Previous_Owners       0
Accidents_Reported    0
Service_Score         0
Resale_Price_Lakh     0
dtype: int64

In [6]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [7]:
df.describe()

,Year,Mileage_Km,Engine_CC,Power_BHP,Previous_Owners,Accidents_Reported,Service_Score,Resale_Price_Lakh
count,320.000000,320.000000,320.000000,320.000000,320.000000,320.000000,320.000000,320.000000
mean,2019.537500,74110.203125,1346.703125,150.489688,1.668750,0.243750,76.203125,4.963031
std,3.341367,38885.260771,543.408160,36.665353,0.865369,0.528164,12.745864,3.359259
min,2014.000000,700.000000,600.000000,51.400000,1.000000,0.000000,55.000000,1.200000
25%,2017.000000,46323.250000,1004.750000,128.450000,1.000000,0.000000,64.750000,2.277500
50%,2020.000000,72718.500000,1303.000000,150.750000,1.000000,0.000000,77.000000,4.610000
75%,2022.000000,97951.500000,1635.250000,171.475000,2.000000,0.000000,87.000000,6.835000
max,2025.000000,320000.000000,5000.000000,390.000000,4.000000,2.000000,98.000000,28.500000

In [8]:
numeric_cols = df.select_dtypes(include=np.number).columns

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]

    print(col, ":", len(outliers), "outliers")

Year : 0 outliers
Mileage_Km : 2 outliers
Engine_CC : 6 outliers
Power_BHP : 7 outliers
Previous_Owners : 14 outliers
Accidents_Reported : 63 outliers
Service_Score : 0 outliers
Resale_Price_Lakh : 5 outliers

In [9]:
X = df.drop("Resale_Price_Lakh", axis=1)
y = df["Resale_Price_Lakh"]

print("Features shape:", X.shape)
print("Target shape:", y.shape)

Features shape: (320, 14)
Target shape: (320,)

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training set:", X_train.shape)
print("Testing set:", X_test.shape)

Training set: (256, 14)
Testing set: (64, 14)

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training set:", X_train.shape)
print("Testing set:", X_test.shape)

Training set: (256, 14)
Testing set: (64, 14)

In [12]:
outlier_cols = ["Mileage_Km", "Engine_CC", "Power_BHP"]

for col in outlier_cols:
    Q1 = X_train[col].quantile(0.25)
    Q3 = X_train[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    X_train[col] = X_train[col].clip(lower_bound, upper_bound)
    X_test[col] = X_test[col].clip(lower_bound, upper_bound)

print("Outliers capped successfully.")

Outliers capped successfully.

In [13]:
categorical_cols = X_train.select_dtypes(include="object").columns

print("Categorical Columns:")
print(categorical_cols)

for col in categorical_cols:
    print("\n", col)
    print(X_train[col].unique())

Categorical Columns:
Index(['Car_ID', 'Brand', 'Fuel_Type', 'Transmission', 'City', 'Seller_Type',
       'Condition'],
      dtype='object')

 Car_ID
['CAR0133' 'CAR0318' 'CAR0235' 'CAR0313' 'CAR0233' 'CAR0125' 'CAR0102'
 'CAR0110' 'CAR0255' 'CAR0159' 'CAR0281' 'CAR0032' 'CAR0263' 'CAR0196'
 'CAR0147' 'CAR0219' 'CAR0094' 'CAR0138' 'CAR0060' 'CAR0117' 'CAR0007'
 'CAR0197' 'CAR0031' 'CAR0023' 'CAR0273' 'CAR0289' 'CAR0057' 'CAR0166'
 'CAR0119' 'CAR0205' 'CAR0082' 'CAR0146' 'CAR0040' 'CAR0220' 'CAR0148'
 'CAR0182' 'CAR0316' 'CAR0109' 'CAR0270' 'CAR0067' 'CAR0198' 'CAR0019'
 'CAR0185' 'CAR0114' 'CAR0020' 'CAR0183' 'CAR0093' 'CAR0080' 'CAR0221'
 'CAR0153' 'CAR0073' 'CAR0097' 'CAR0016' 'CAR0112' 'CAR0011' 'CAR0181'
 'CAR0070' 'CAR0098' 'CAR0302' 'CAR0069' 'CAR0256' 'CAR0038' 'CAR0127'
 'CAR0017' 'CAR0229' 'CAR0068' 'CAR0257' 'CAR0248' 'CAR0126' 'CAR0165'
 'CAR0087' 'CAR0305' 'CAR0145' 'CAR0272' 'CAR0141' 'CAR0234' 'CAR0300'
 'CAR0209' 'CAR0307' 'CAR0207' 'CAR0130' 'CAR0039' 'CAR0222' 'CAR0304'
 'CAR0156' 'CAR0113' 'CAR0268' 'CAR0118' 'CAR0297' 'CAR0309' 'CAR0291'
 'CAR0176' 'CAR0200' 'CAR0155' 'CAR0303' 'CAR0003' 'CAR0116' 'CAR0164'
 'CAR0224' 'CAR0121' 'CAR0240' 'CAR0278' 'CAR0128' 'CAR0075' 'CAR0030'
 'CAR0084' 'CAR0266' 'CAR0108' 'CAR0174' 'CAR0180' 'CAR0134' 'CAR0254'
 'CAR0246' 'CAR0296' 'CAR0066' 'CAR0226' 'CAR0086' 'CAR0243' 'CAR0160'
 'CAR0013' 'CAR0036' 'CAR0029' 'CAR0171' 'CAR0143' 'CAR0267' 'CAR0132'
 'CAR0210' 'CAR0052' 'CAR0096' 'CAR0239' 'CAR0179' 'CAR0251' 'CAR0042'
 'CAR0090' 'CAR0247' 'CAR0137' 'CAR0027' 'CAR0314' 'CAR0142' 'CAR0228'
 'CAR0001' 'CAR0288' 'CAR0275' 'CAR0292' 'CAR0101' 'CAR0193' 'CAR0276'
 'CAR0104' 'CAR0172' 'CAR0099' 'CAR0037' 'CAR0250' 'CAR0062' 'CAR0151'
 'CAR0048' 'CAR0230' 'CAR0280' 'CAR0012' 'CAR0317' 'CAR0201' 'CAR0287'
 'CAR0028' 'CAR0249' 'CAR0005' 'CAR0123' 'CAR0033' 'CAR0232' 'CAR0163'
 'CAR0238' 'CAR0284' 'CAR0139' 'CAR0063' 'CAR0216' 'CAR0136' 'CAR0299'
 'CAR0129' 'CAR0311' 'CAR0009' 'CAR0071' 'CAR0283' 'CAR0065' 'CAR0045'
 'CAR0015' 'CAR0157' 'CAR0041' 'CAR0306' 'CAR0124' 'CAR0295' 'CAR0262'
 'CAR0217' 'CAR0154' 'CAR0024' 'CAR0279' 'CAR0237' 'CAR0208' 'CAR0213'
 'CAR0293' 'CAR0252' 'CAR0312' 'CAR0202' 'CAR0162' 'CAR0044' 'CAR0218'
 'CAR0191' 'CAR0260' 'CAR0106' 'CAR0054' 'CAR0002' 'CAR0050' 'CAR0081'
 'CAR0206' 'CAR0035' 'CAR0264' 'CAR0092' 'CAR0053' 'CAR0265' 'CAR0242'
 'CAR0014' 'CAR0089' 'CAR0274' 'CAR0167' 'CAR0315' 'CAR0135' 'CAR0308'
 'CAR0244' 'CAR0055' 'CAR0051' 'CAR0175' 'CAR0190' 'CAR0319' 'CAR0188'
 'CAR0170' 'CAR0059' 'CAR0049' 'CAR0236' 'CAR0253' 'CAR0022' 'CAR0161'
 'CAR0277' 'CAR0192' 'CAR0294' 'CAR0258' 'CAR0150' 'CAR0131' 'CAR0152'
 'CAR0100' 'CAR0088' 'CAR0215' 'CAR0122' 'CAR0320' 'CAR0021' 'CAR0189'
 'CAR0072' 'CAR0107' 'CAR0271' 'CAR0103']

 Brand
['Volkswagen' 'Mahindra' 'Renault' 'Toyota' 'Maruti' 'Kia' 'Skoda' 'Tata'
 'Hyundai' 'Honda']

 Fuel_Type
['Diesel' 'Petrol' 'Electric' 'CNG']

 Transmission
['Manual' 'Automatic']

 City
['Lucknow' 'Delhi' 'Kochi' 'Pune' 'Hyderabad' 'Chandigarh' 'Ahmedabad'
 'Mumbai' 'Bengaluru' 'Jaipur']

 Seller_Type
['Certified Dealer' 'Dealer' 'Individual']

 Condition
['Very Good' 'Good' 'Poor' 'Excellent' 'Fair']

In [14]:
X_train = X_train.drop("Car_ID", axis=1)
X_test = X_test.drop("Car_ID", axis=1)

print("Car_ID dropped successfully.")

Car_ID dropped successfully.

In [15]:
condition_order = [["Poor", "Fair", "Good", "Very Good", "Excellent"]]

ordinal_encoder = OrdinalEncoder(categories=condition_order)

X_train["Condition"] = ordinal_encoder.fit_transform(
    X_train[["Condition"]]
)

X_test["Condition"] = ordinal_encoder.transform(
    X_test[["Condition"]]
)

print("Condition encoded successfully.")

Condition encoded successfully.

In [16]:
nominal_cols = [
    "Brand",
    "Fuel_Type",
    "Transmission",
    "City",
    "Seller_Type"
]

encoder = OneHotEncoder(
    handle_unknown="ignore",
    sparse_output=False
)

# Learn categories from training data
train_encoded = encoder.fit_transform(X_train[nominal_cols])

# Apply same encoding to test data
test_encoded = encoder.transform(X_test[nominal_cols])

In [17]:
encoded_columns = encoder.get_feature_names_out(nominal_cols)

train_encoded_df = pd.DataFrame(
    train_encoded,
    columns=encoded_columns,
    index=X_train.index
)

test_encoded_df = pd.DataFrame(
    test_encoded,
    columns=encoded_columns,
    index=X_test.index
)

print("One-Hot Encoding completed.")
print("New encoded columns:", len(encoded_columns))

One-Hot Encoding completed.
New encoded columns: 29

In [18]:
X_train = X_train.drop(columns=nominal_cols)
X_test = X_test.drop(columns=nominal_cols)

X_train = pd.concat([X_train, train_encoded_df], axis=1)
X_test = pd.concat([X_test, test_encoded_df], axis=1)

print("Training shape:", X_train.shape)
print("Testing shape:", X_test.shape)

X_train.head()

Training shape: (256, 37)
Testing shape: (64, 37)

,Year,Mileage_Km,Engine_CC,Power_BHP,Condition,Previous_Owners,Accidents_Reported,Service_Score,Brand_Honda,Brand_Hyundai,...,City_Delhi,City_Hyderabad,City_Jaipur,City_Kochi,City_Lucknow,City_Mumbai,City_Pune,Seller_Type_Certified Dealer,Seller_Type_Dealer,Seller_Type_Individual
132,2018,65330.0,1188,159.8,3.0,1,0,71,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
317,2022,76484.0,1038,139.6,2.0,1,1,69,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
234,2015,112800.0,1279,163.5,2.0,1,0,70,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
312,2023,66420.0,1549,163.3,2.0,2,0,79,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
232,2016,98325.0,1687,136.2,3.0,2,0,78,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [19]:
scale_cols = [
    "Year",
    "Mileage_Km",
    "Engine_CC",
    "Power_BHP",
    "Previous_Owners",
    "Accidents_Reported",
    "Service_Score"
]

In [20]:
scaler = StandardScaler()

X_train[scale_cols] = scaler.fit_transform(X_train[scale_cols])
X_test[scale_cols] = scaler.transform(X_test[scale_cols])

print("Feature scaling completed.")

Feature scaling completed.

In [21]:
print("Final Training Shape:", X_train.shape)
print("Final Testing Shape:", X_test.shape)

print("\nMissing values in training data:")
print(X_train.isnull().sum().sum())

print("\nMissing values in testing data:")
print(X_test.isnull().sum().sum())

X_train.head()

Final Training Shape: (256, 37)
Final Testing Shape: (64, 37)

Missing values in training data:
0

Missing values in testing data:
0

,Year,Mileage_Km,Engine_CC,Power_BHP,Condition,Previous_Owners,Accidents_Reported,Service_Score,Brand_Honda,Brand_Hyundai,...,City_Delhi,City_Hyderabad,City_Jaipur,City_Kochi,City_Lucknow,City_Mumbai,City_Pune,Seller_Type_Certified Dealer,Seller_Type_Dealer,Seller_Type_Individual
132,-0.486391,-0.225883,-0.322882,0.304485,3.0,-0.734379,-0.442634,-0.454105,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
317,0.725445,0.089371,-0.656431,-0.330444,2.0,-0.734379,1.477948,-0.614672,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
234,-1.395268,1.115798,-0.120529,0.420784,2.0,-0.734379,-0.442634,-0.534389,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
312,1.028404,-0.195076,0.479859,0.414498,2.0,0.433329,-0.442634,0.188165,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
232,-1.092309,0.706680,0.786724,-0.437314,3.0,0.433329,-0.442634,0.107881,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [22]:
train_processed = X_train.copy()
train_processed["Resale_Price_Lakh"] = y_train

test_processed = X_test.copy()
test_processed["Resale_Price_Lakh"] = y_test

print("Processed training data:", train_processed.shape)
print("Processed testing data:", test_processed.shape)

Processed training data: (256, 38)
Processed testing data: (64, 38)

In [23]:
final_processed = pd.concat(
    [train_processed, test_processed],
    axis=0
).sort_index()

final_processed.to_csv(
    "Day12_Preprocessed_Used_Car_Dataset.csv",
    index=False
)

print("Processed dataset saved successfully!")
print("Final dataset shape:", final_processed.shape)

Processed dataset saved successfully!
Final dataset shape: (320, 38)

In [ ]:
from google.colab import files

files.download("Day12_Preprocessed_Used_Car_Dataset.csv")